gpus: 8
num_samples: 2474251
batch_size: 4
dataset: scannet
num_nodes: 1
arch: resnet50
hidden_mlp: 2048
feat_dim: 128
warmup_epochs: 10
max_epochs: 100
temperature: 0.1
first_conv: true
maxpool1: true
optimizer: adam
lars_wrapper: true
exclude_bn_bias: false
start_lr: 0.0
learning_rate: 0.001
final_lr: 0.0
weight_decay: 1.0e-06
